### ISSUE TITLE
Healthcheck Endpoint

### ISSUE THREAD

**Issue by pmd5700** [sdr-enthusiasts/docker-dump978#58]
Would it be possible to add a healthcheck endpoint, similar to Readsb? I have dump978 running and for some reason, the dongle will stop working. I won't know until I happen to go into the piaware dashboard and see that it's not online.

**Comment by mikenye** [comment]
Hi @pmd5700,

Which healthcheck endpoint are you referring to? The [prometheus endpoint](https://github.com/sdr-enthusiasts/docker-readsb-protobuf#prometheus-options)?

**Comment by pmd5700** [comment]
This one: https://github.com/sdr-enthusiasts/docker-readsb-protobuf/pull/46 I was going to use something like this with Home Assistant to alert me if it went bad. Not sure if it would even work the way I want. Oddly enough (or not that odd), I pulled all the dongles and reseated them and rebooted and haven't had the issue in about 2 weeks :D

**Comment by mikenye** [comment]
Done!

**Comment by kx1t** [comment]
> I guess I should have thought more about this...what does the URL end up being? The readsb is something like 192.168.1.100:8080/health, but dump978 doesn't have a port like that, right?

In order to see the healthcheck from outside the container, you need to map a host port to port 80 in the container. This is done by (for example) adding `-p 8080:80` to your `docker run` command, or by adding 
```
     ports:
        - 8080:80
```
to your `docker-compose.yml` file. Of course, substitute `8080` by whatever works for you.
Once you have done this (and recreated the container), the health check will be available at http://my_host_ip:8080/health

**Comment by pmd5700** [comment]
Oh that makes sense...I guess I was thinking the code had to be written to have an open port like that. But that worked perfectly. Thanks!
